[package]
name = "rokol_learn_opengl"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[dependencies]
rokol = { git = "https://github.com/toyboot4e/rokol", branch = "master", features = ["glcore33"] }

log = "0.4.14"
env_logger = "0.8.3"
image = "0.23.13"

